export type Squares = [
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
{square: number},
];
