export type State = {
  countdownTimer: number,
  gameOver: string,
  points: number,
  clicked: boolean,
  moleImage: string,
  activeGame: boolean,
  moles: number,
  chanceNumber: number,
  squares: [
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
  ]
}