export type State = {
  counter: number,
  gameOver: string,
  points: number,
  clicked: boolean,
  moleImage: string,
  activeGame: boolean,
  moles: number,
  list: number [],
  squares: [
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
  ]
}