export type State = {
  counter: number,
  gameOver: string,
  points: number,
  clicked: boolean,
  moleImage: string,
  moleUp: boolean,
  lastHole: number,
  ids: [
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
    id: boolean,
  ]
}